os:
  - linux
dist:
  - xenial
language: node_js
node_js:
  - "lts/*"
cache: npm
install:
  - npm install -g ionic
before_script:
  - npm install
script:
  - ionic build --prod
deploy:
  strategy: git
  provider: pages
  token: $GITHUB_TOKEN
  target_branch: gh-pages
  local_dir: www
  skip_cleanup: true
  on:
    branch: main
